:PROPERTIES:
:header-args:C: :results scalar :exports both :eval none-export
:END:
#+title: C 语言项目案例
* 网络通信编程
** windows
** linux 上 socket 编程
https://www.binarytides.com/socket-programming-c-linux-tutorial/
*** 创建 socket
socket 编程的第一件事就是创建一个 socket. *socket* 函数提供了该功能. 下面是代码
示例:
#+begin_src C
#include <stdio.h>
#include <sys/socket.h>

int main(int argc, char *argv[]){
  int socket_desc;
  socket_desc = socket(AF_INET, SOCK_STREAM, 0);

  if(socket_desc == -1){
    printf("Could not create socket");
  }
  return 0;
}
#+end_src
socket 函数创建一个套接字描述符. 其定义如下:
#+begin_src C
#include <sys/types.h>
#include <sys/socket.h>

int socket(int domain, int type, int protocol);
#+end_src

domain 指定要创建的套接字的协议族, type 指定套接字的类型, protocol 指定使用哪种
协议. socket() 函数执行成功时,返回一个正整数,称为套接字描述符,用来标识这个套接字,否
则，返回 -1.

#+CAPTION: domain 的取值
| 值        | 含义                          |
| AF_UNUNIX | 域协议族,本机的进程通信时使用 |
| AF_INET   | Internet 协议族               |
| AF_ISO    | ISO 协议族                    |

#+CAPTION: type 的取值
| 值          | 含义                                                       |
| SOCK_STREAM | 流套接字,面向连接的和可靠的通信类型                        |
| SOCK_DGRAM  | 数据报套接字, 面向非链接的和不可靠的通信类型               |
| SOCK_RAW    | 原始套接字,只对 Internet 协议有效,可以用来直接访问 IP 协议 |

参数 protocol 通常设置为0, 表示使用默认协议,如 Internet 协议族的流套接字使用 TCP
协议,而数据报套接字使用 UDP 协议. 当套接字是原始套接字类型时,需要指定参数
protocol, 因为原始套接字对多种协议有效, 如 ICMP 和 IGMP 等.

上面示例代码里创建流套接字,使用 Internet 协议族,也就是使用 TCP 协议进行通信的套
接字.
下面我们将尝试通过该套接字连接到网站服务器(www.google.com 国内环境原因,改为 www.baidu.com).
*** 通过 socket 链接到服务器
我们通过特定的端口号连接到远程服务器.所以,我们需要两个信息, IP 地址和端口号.

要连接到一个远程服务器,我们需要做几件事情. 首先是创建一个有着正确值的 sockaddr_in
结构.
#+begin_src C
struct sockaddr_in server;
#+end_src
来看看这个结构的组成:
#+begin_src C
// IPv4 AF_INET sockets:
struct sockaddr_in{
  short sin_family;		// e.g. AF_INET, AF_INET6
  unsigned short sin_port;	// e.g. htons(3490)
  struct in_addr sin_addr;	// 参见下面的 in_addr 结构定义
  char sin_zero[8];		// 如果需要,可用来清零的
};

struct in_addr{
  unsigned long s_addr;		// 用 inet_pton() 加载
};

struct sockaddr{
  unsigned short  sa_family;	// 地址族, AF_XXX
  char sa_data[14];		// 14 字节的协议地址
};
#+end_src

sockaddr_in 有一个叫做 sin_addr 的 in_addr 结构类型成员,该类型只包含一个无符号长
整型,该值是 IP 地址的长整型格式.

inet_addr() 函数是一个非常有用的函数,它用来将 IP 地址转换为一个长整型格式.使用示
例:
#+begin_src C
server.sin_addr._s_addr = inet_addr("74.125.235.20");
#+end_src
所以我们需要知道正要连接的远程服务器的 IP 地址. 上面的例子里使用的是
www.google.com 的 IP 地址作为示例,随后我们会介绍如何找到给定域名的 IP 地址.

最后一件事,我们需要的是 connetc() 函数, 该函数需要一个套接字和一个 sockaddr 结构
来连接. 下面是代码示例:
#+begin_src C
#include <stdio.h>
#include <sys/socket.h>
#include <arpa/inet.h> // inet_addr()

int main(int argc, char * argv[]) {

  int socket_desc;
  struct sockaddr_in server;

  /* 创建一个 socket */
  socket_desc = socket(AF_INET, SOCK_STREAM, 0);
  if(socket_desc == -1)
    {
      printf("Could not create socket");
    }

  server.sin_addr.s_addr = inet_addr("14.215.177.39");
  server.sin_family = AF_INET;
  server.sin_port = htons(80);


  /* 连接到服务器 */
  if(connect(socket_desc, (struct sockaddr *)&server, sizeof(server)) < 0)
    {
      puts("Connect error!");
      return 1;
    }
  puts("Connected!");
  return 0;
}
#+end_src

#+RESULTS:
: Connected!

这再简单不过了吧. 上面的代码创建了一个 socket 并且用它建立了连接.当你尝试连接其
他端口号时,你应该不会连接成功,因为这表明了该端口并没有开启用于连接.

现在,我们已经成功连接的服务器,下面,让我们来向服务器发送一些数据.

#+begin_quote
"连接" 这个概念仅仅应用于 SOCK_STREAM/TCP 类型的套接字. 连接意味着可靠的数据流,
这样的数据流可以有多个,每个流都有自己的通信,可以将其视为不受其他数据干扰的管道.

其他的套接字如 UDP, ICMP, ARP 没有 "连接" 的概念, 这些都是基于非连接的通信. 这意
味着不断地发送或接收来自任何人的数据包.
#+end_quote
*** 通过 socket 发送数据
send() 函数可以简单地发送数据. 它需要一个 socket 描述符, 要发送的数据以及数据大
小. 下面是一个非常简单的示例用来向 www.baidu.com 的 IP 地址发送一些数据.
#+begin_src C
#include <stdio.h>
#include <string.h>
#include <sys/socket.h>
#include <arpa/inet.h> // inet_addr

int main(int argc, char * argv[]) {

  int socket_desc;
  struct sockaddr_in server;
  char * message;

  /* 创建一个 socket */
  socket_desc = socket(AF_INET, SOCK_STREAM, 0);
  if(socket_desc == -1)
    {
      printf("Could not create socket");
    }

  server.sin_addr.s_addr = inet_addr("14.215.177.39"); // the IP of www.baidu.com
  server.sin_family = AF_INET;
  server.sin_port = htons(80);


  /* 连接到服务器 */
  if(connect(socket_desc, (struct sockaddr *)&server, sizeof(server)) < 0)
    {
      puts("Connect error!");
      return 1;
    }
  puts("Connected!");


  /* 发送数据 */
  message = "GET / HTTP/1.1\r\n\r\n";
  if(send(socket_desc,message, strlen(message), 0) < 0)
    {
      puts("Send failed!");
      return 1;
    }
  puts("Data Send\n");
  return 0;
}
#+end_src

#+RESULTS:
: Connected!
: Data Send
:

上面的例子里,我们连接到一个 IP 地址,并发送了一个字符串消息 "GET /
HTTP/1.1\r\n\r\n" 到该 IP 代表的服务器.

该消息实际上是一条 http 命令,是用来获取网站的主页用的.

现在,我们向服务器发送了一些数据,是时候接收来自服务器的回应了.

#+begin_quote
当向 socket 发送数据的时候,你基本上就是在向该 socket 写入数据.这和写入文件非常相
似,因此,你也可以使用 write() 函数来向 socket 发送数据. 后面我们会使用 write() 函
数来发送数据.
#+end_quote
*** 从 socket 接收数据
函数 recv() 是用来在 socket 上接收数据的. 下面的例子里,我们会向服务器发送上个例
子里相同的消息,并从服务器接收回复.
#+begin_src C
#include <stdio.h>
#include <string.h>
#include <sys/socket.h>
#include <arpa/inet.h> // inet_addr

int main(int argc, char * argv[]) {

  int socket_desc;
  struct sockaddr_in server;
  char * message, server_reply[2000];

  /* 创建一个 socket */
  socket_desc = socket(AF_INET, SOCK_STREAM, 0);
  if(socket_desc == -1)
    {
      printf("Could not create socket");
    }
  server.sin_addr.s_addr = inet_addr("14.215.177.38");
  server.sin_family = AF_INET;
  server.sin_port = htons(80);


  /* 连接到服务器 */
  if(connect(socket_desc, (struct sockaddr *)&server, sizeof(server)) < 0)
    {
      puts("Connect error!");
      return 1;
    }
  puts("Connected!");


  /* 发送数据 */
  message = "GET / HTTP/1.1\r\n\r\n";
  if(send(socket_desc,message, strlen(message), 0) < 0)
    {
      puts("Send failed!");
      return 1;
    }
  puts("Data Send");

  /* 从服务器接收回复 */
  if(recv(socket_desc, server_reply, sizeof(server_reply),0) < 0)
    {
      puts("Recv failed!");
    }
  puts("Reply received!\n");
  puts(server_reply);
  return 0;
}
#+end_src

#+RESULTS:
#+begin_example
Connected!
Data Send
Reply received!

HTTP/1.1 200 OK
Accept-Ranges: bytes
Cache-Control: no-cache
Connection: keep-alive
Content-Length: 9508
Content-Type: text/html
Date: Fri, 23 Dec 2022 14:20:28 GMT
P3p: CP=" OTI DSP COR IVA OUR IND COM "
P3p: CP=" OTI DSP COR IVA OUR IND COM "
Pragma: no-cache
Server: BWS/1.1
Set-Cookie: BAIDUID=73CAF0920E9800261EB221B691D93EAD:FG=1; expires=Thu, 31-Dec-37 23:55:55 GMT; max-age=2147483647; path=/; domain=.baidu.com
Set-Cookie: BIDUPSID=73CAF0920E9800261EB221B691D93EAD; expires=Thu, 31-Dec-37 23:55:55 GMT; max-age=2147483647; path=/; domain=.baidu.com
Set-Cookie: PSTM=1671805228; expires=Thu, 31-Dec-37 23:55:55 GMT; max-age=2147483647; path=/; domain=.baidu.com
Set-Cookie: BAIDUID=73CAF0920E9800268BCC9A2A6B99B559:FG=1; max-age=31536000; expires=Sat, 23-Dec-23 14:20:28 GMT; domain=.baidu.com; path=/; version=1; comment=bd
Traceid: 167180522802383180907255949292488709478
Vary: Accept-Encoding
X-Frame-Options: sameorigin
X-Ua-Compatible: IE=Edge,chrome=1

<!DOCTYPE html><html><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"><meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"><meta content="always" name="referrer"><meta name="description" content="全球领先的中文搜索引擎、致力于让网民更便捷地获取信息，找到所求。百度超过千亿的中文网页数据库，可以瞬间找到相关的搜索结果。"><link rel="shortcut icon" href="//www.baidu.com/favicon.ico" type="image/x-icon"><link rel="search" type="application/opensearchdescription+xml" href="//www.baidu.com/content-search.xml" title="百度搜索"><title>百度一下，你就知道</title><style type="text/css">body{margin:0;padding:0;text-align:center;background:#fff;height:100%}html{overflow-y:auto;color:#000;overflow:-moz-scrollbars;height:100%}body,input{font-size:12px;font-family:"PingFang SC",Arial,"Microsoft YaHei",sans-serif}a{text-decoration:none}a:hover{text-decoration:underline}img{border:0;-ms-interpolation-mode:bicubic
#+end_example


我们可以看到服务器发送的回复是什么内容. 它看起来像是 HTML, 好吧,它就是
HTML. baidu.com 回复了我们请求的页面的内容. 这很简单吧!

#+begin_quote
当从 socket 接收数据时,我们根本上来讲是从 socket 上读取数据. 这和从文件中读取数
据类似. 所以哦我们也可以使用 read() 函数来从 socket 读取数据. 例如:
#+begin_src C
read(socket_desc, server_reply, 2000);
#+end_src
#+end_quote
*** 关闭 socket
函数 close() 是用来关闭 socket 的. 使用它需要包含 unistd.h 头文件.
#+begin_src C
close(socket_desc);
#+end_src
*** 获取域名的 IP 地址
当连接到远程主机时,知道它的 IP 地址是很有必要的. 函数 gethostbyname() 就是用来获
取 ip 地址的. 它接收一个域名作为参数,并返回一个 hostent 类型的结构. 这个结构里就
包含了 ip 信息. 该结构的定义位于 netdb.h 头文件. 让我们来看一下这个结构体的组成.
#+begin_src C
/* Description of data base entry for a single host.  */
struct hostent
{
  char *h_name;			/* Official name of host.  */
  char **h_aliases;		/* Alias list.  */
  int h_addrtype;		/* Host address type.  */
  int h_length;			/* Length of address.  */
  char **h_addr_list;		/* List of addresses from name server.  */
};
#+end_src
h_addr_list 里有 IP 地址信息.所以让我们看看如何使用它的示例代码:
#+begin_src C

/* 获取域名对应的 IP 地址 */
#include <netinet/in.h>
#include <stdio.h>
#include <string.h>
#include <sys/socket.h>
#include <netdb.h> // hostent
#include <arpa/inet.h> // inet_addr()

int main(int argc, char * argv[]) {

  char *hostname = "www.baidu.com";
  char ip[100];
  struct hostent *he;
  struct in_addr ** addr_list;
  int i;
  if((he=gethostbyname(hostname)) == NULL)
    {
      herror("gethostbyname");
      return 1;
    }
  addr_list = (struct in_addr **) he -> h_addr_list;
  for(i = 0; addr_list[i] != NULL; i++)
    {
      strcpy(ip , inet_ntoa(*addr_list[i]) );
    }
  printf("%s resolved to: %s", hostname, ip);
  return 0;
}
#+end_src

#+RESULTS:
: www.baidu.com resolved to: 14.215.177.38

上面的代码可以找出任意域名的 IP 地址,然后找到的 IP 地址可以用来通过 socket 建立
连接.

inet_ntoa() 函数会将长整型的 IP 地址转换成点格式(192.168.0.1 这种). 它和
inet_addr() 函数刚好相反.

目前位置,我们已经使用过了一些重要的结构体, 让我们来回顾一下:
+ sockaddr_in :: 连接信息,用于 connect(), send(), recv() 等函数.
+ in_addr :: 长整型格式的 IP 地址信息.
+ sockaddr ::
* MP3 播放器(命令行,Linux)
简单实现一个运行于Linux终端的 mp3 文件播放器.

音频电流是连续变化的,和声波振动相对应.振动位移也是连续变化的,不可能从一个位置跳
跃到另一个位置, 对于声音的这种连续变化的波形信息,是无法完整记录下来的,因此,用计
算机记录声音时,必须对连续的声音进行一定的处理,处理方法就是采样和量化:
+ 采样 :: 在特定的时刻对模拟信号进行测量记录就叫做采样,采样只保留了声音的部分信
  息,所以会损失声音的一些信息. 但是只要采样的点足够多,基本上就可以反映声音的原始
  信息,损失的是极短时间内发生的一些变化,即很高的频率成分信息.
+ 量化 :: 采样得到的值的幅度可以是无穷多实数中的一个,这些值要用二进制表示,就必须
  为每个值分配一个编码,显然,对无穷多个值分配编码是不可能的.如果把信号的幅度取值
  的数目加以限制,量化后得到的值只能取有限个参考值,当实际值不在该范围内时,可以进
  行舍入,比如限定取值在 0,0.1,0.2,0.3,...0.7,这些参考值,而实际采集到的值为
  0.123V ,就把它算作是 0.1V, 这样,需要编码的值就大大减少了.这种处理就叫做量化.


经过上面两步,声音数据就成了可以被计算机处理的值了,这些值还要经过下面步骤才能称为
我们使用的音频文件:
+ 编码 :: 计算机是用编码的形式来表示符号和数值的,量化后得到的每个数据值,都可以用
  一个分配的编码表示,这种将量化的值表示为不同编码的过程,就叫做编码.
+ 压缩编码 :: 经过编码后,每次采集得到的样本数据要保存,都需要大量的储存空间.事实
  上,声音数据里,有很多冗余的数据,一方面,声音的变化是连续的,前后时刻的采集点间差
  别并不大,因此没有必要完整记录每个样本的值.可以记录一个样本的值后,在记录下它与
  后一个样本值之间的差值,因为差值较小,可以用较小的采样精度(量化位数--量化时参考
  值的个数)表示,就减少了储存空间的开销.另一方面,不是所有的声音都会被人耳所感知,
  人耳对同一时间发出的多种声音,通常并不能完全听到,总有比较 "重要" 的声音会盖过其
  他声音,因此,我们可以将声音分为多个频段,对于这些人耳不"敏感"的声音,采用较小的采
  样精度,这样也能大大减少储存空间的开销.


经过采集,量化,编码,压缩后的声音数据就是能反映原始声音信息的数据了,它是计算机可处
理的数据,不过需要将这些数据按一定方式进行组织形成文件之后才方便数据的保存和传输.

根据采样频率,量化位数,编码方式,压缩算法,文件组织方式等分为多种音频文件格式,我要
播放的就是 MP3 格式的音频文件. 因为最开始是学习的
https://github.com/Mapc1/Mp3-cli 该开源项目,所以使用的是 PulseAudio 和 mpg123 软
件提供的 API 进行功能的实现,它们一个提供应用程序和硬件的交互接口,一个负责将音频
文件解压缩,解码成硬件可处理的字节数据. PulseAudio 负责将数据流传输到硬件设备实现
播放音频数据, mpg123 负责将音频文件解码成硬件设备可读取的数据流,完成解码操作. 其
实也有其他软件可以实现,比如 ffmpeg 同时提供了解码和播放操作的API, 使用它就不需要
使用两个软件的 API 了; 不过 ffmpeg 需要额外安装,而 PulseAudio 大部分 Linux 发行
版都自带了,事实上, PulseAudio 的依赖库中有一个 libsndfile 库,它是用来提供音频文
件读写的,它将文件的解码操作隐藏到程序 API 中了, mpg123 则是一个音频文件解码和播
放的库,它应该是需要额外安装的,所以在用 mpg123 实现功能后,会考虑用 libsndfile 再
次实现播放功能.

** [[https://www.freedesktop.org/wiki/Software/PulseAudio/][PulseAudio]]
PulseAudio 是一个 POSIX 操作系统上的音频服务器系统,意味着它是你的声音应用程序的
代理. 当音响数据在应用程序和硬件之间传递时,它对音响数据执行一些高级操作. 该程序
是所有相关的现代 Linux 发行版本的不可缺少的一部分,并且被多家供应商用于各种移动设
备.像是传输音频到不同的机器,改变歌曲格式或通道数,有或是将几种音频数据混合作为一
个输入/输出等都可以通过 PulseAudio 轻松完成.

我们先暂时只考虑实现最基本的播放 mp3 文件的功能,其他的以后再论.使用该系统开发自
己的音频播放程序可以阅读其[[https://www.freedesktop.org/wiki/Software/PulseAudio/Documentation/Developer/][开发者文档]]. 该文档给出了使用它开发客户端应用程序的 API
文档,因为我们现在只需要实现基本的播放功能,所以只用到给出的 [[https://freedesktop.org/software/pulseaudio/doxygen/simple.html][Simple API]].
*** Simple API
简单API 是为那些具有基本播放或记录功能的应用程序设计的.它只能支持每个连接单个数
据流,并且不支持处理复杂的功能,比如事件,通道映射和音量控制. 然而,这对大多数的程序
来说已经足够了. 下面的代码示例都是在线文档中的例子,在线文档中这些例子里使用的结
构体原型,函数原型等都可点击查看,需要查看详情的可以访问在线文档: [[https://freedesktop.org/software/pulseaudio/doxygen/simple.html][Simple API]] .
**** 连接
使用音频系统的第一步就是连接到音频服务器,通常是这样做到:
#+begin_src C
pa_simple *s;
pa_sample_spec ss;

ss.format = PA_SAMPLE_S16NE;
ss.channels = 2;
ss.rate = 44100;

s = pa_simple_new(NULL,		// 使用默认服务器
		  "Fooapp",	// 我们应用程序的名字
		  PA_STREAM_PLAYBACK,
		  NULL,		// 使用默认设备
		  "Music",	// 数据流的描述
		  &ss,		// 采样格式
		  NULL,		// 使用默认的通道映射
		  NULL,		// 使用默认的缓冲区属性
		  NULL,		// 忽略错误代码
		  );
#+end_src
到了这一步,s 就是返回的一个已连接的对象,或是有连接错误则为返回的 NULL 值.
**** 传输数据
一旦与服务器建立了连接,就可以开始传输数据了.使用连接和普通的系统调用 read() 和
write() 函数非常相似. 主要的不同是它们叫做 pa_simple_read() 和
pa_simple_write(). 请注意,这些操作都是阻塞式的.
pa_simple_write() 的函数原型:
#+begin_src C
int pa_simple_write(pa_simple *s,
const void *data,
size_t bytes,
int *error );
#+end_src
+ 第一个参数是服务器连接对象的指针
+ 第二个参数是储存数据的变量的指针
+ 第三个数据是写入的数据的字节数
+ 第四个参数是发生错误时记录错误代码的指针


该函数成功时返回 0 ,错误时返回负值. pa_simple_read() 的原型与 pa_simple_write()
的基本一致,不过是从服务器连接中读取数据而已.
**** 控制
+ pa_simple_get_latency() :: 会分别返回播放或记录通道的总延迟.
+ pa_simple_flush() :: 会丢弃当前在缓冲区里的所有数据.


如果当前正有一个数据流在使用中,则下面的操作是可用的:
+ pa_simple_drain() :: 会等待所有已发送的数据完成播放.
**** 清理
一旦播放或记录完成,连接就应该被关闭,资源也应该被释放. 这通过下面代码完成:
#+begin_src C
pa_simple_free(s);
#+end_src

** mpg123
mpg123 是用于播放和解码音频文件的库,其 API 文档可以在这里查阅
[[https://mpg123.de/api/]] . 我们第一步只想实现打开一个 mp3 文件,并将其播放出来的功
能,因此只需要用到 [[https://mpg123.de/api/group__mpg123__input.shtml][文件输入和解码]] 模块提供的功能,主要使用的函数就是
[[https://mpg123.de/api/group__mpg123__input.shtml#ga9b9f65f86d9c79997a4bf58ad13a10f5][mpg123_open_fixed()]], 其函数原型为:
#+begin_src C
MPG123_EXPORT int mpg123_open_fixed 	(
	        mpg123_handle *  	mh,
		const char *  	path,
		int  	channels,
		int  	encoding 
	);
#+end_src

+ 第一个参数为 libmpg123 的解码器句柄的指针,是一个不透明结构体(不用知道定义,可以
  直接用它定义变量使用),多数的函数都以它作为第一个参数,并且通过它来操作读取的数
  据.
+ 第二个参数是要打开的音频文件的路径;
+ 第三个参数是频道数(双通道2,单通道1);
+ 第四个参数是编码格式;


该函数会按固定的属性打开音频文件,并将其转换为字节流数据,然后可以通过句柄指针 mh
访问字节流数据,这些字节流数据还并没有进行解码,还需要通过 mpg123_read() 函数来读
取字节流数据并进行解码,其函数原型:
#+begin_src C
MPG123_EXPORT int mpg123_read(
mpg123_handle *mh,
void *outmemory,
size_t outmemsize,
size_t *done );
#+end_src
+ 第一个参数是解码器句柄
+ 第二个参数是解码后的数据写入的变量的地址
+ 第三个参数是最大的写入字节数
+ 第四个参数是实际解码数量的存放地址


该函数可以从字节流中解码出最大 outmemsize 数量的数据,而实际的解码数存放在指针
done 储存的地址所代表的变量中.
** 实现播放功能
首先需要从命令行接收文件名/文件路径参数:
#+begin_src C
/* mp3 player on linux */
#include <stdio.h>

int main(int argc, char *argv[])
    {
      if(argc <= 1)
	{
	  fprintf (stderr, "Error!\nThis program requires the path of the mp3 files as an argument!\n");
	}
      else {
	printf("%s\n",argv[1]);
      }
      return 0;
    }
#+end_src

然后就可以用 mpg123 库将音频文件转为字节流数据
#+begin_src C
/* mp3 player on linux */
#include <stdint.h>
#include <fmt123.h>
#include <stddef.h>
#include <stdio.h>
#include <mpg123.h>

#define BUFSIZE 1024

int main(int argc, char *argv[])
    {
      mpg123_handle * handle;
      /* uint8_t buf[BUFSIZE]; // */
      char buf[BUFSIZE]; //
      if(argc <= 1)
	{
	  fprintf (stderr, "Error!\nThis program requires the path of the mp3 files as an argument!\n");
	}
      else {
	printf("%s\n",argv[1]);
      }

      handle = mpg123_new(NULL, NULL);
      mpg123_open_fixed(handle, argv[1], 2, MPG123_ENC_SIGNED_16);

      size_t decoded = 1;
      /* 从 handle 里读取 bufsize 大小的数据到 buf 中 */
      mpg123_read(handle, buf, BUFSIZE, &decoded);

      /* 通过 mpg123 将音频文件的数据解码读取为字节数据并存入 buf 中,
      下面的代码就可以进行字节流数据的播放了 */

      return 0;
    }
#+end_src
到了这里,我们已经把音频数据转为字节流数据了,我们能用 handle 访问字节流数据,上面
的例子里利用 handle 从字节流数据里读取了 BUFSIZE 大小的数据到 buf 中,下面就可以
将数据发送到声音服务器进行播放了
#+begin_src C
/* mp3 player on linux */
#include <fmt123.h>
#include <mpg123.h>
#include <pulse/def.h>
#include <pulse/simple.h>
#include <stddef.h>
#include <stdint.h>
#include <stdio.h>

#define BUFSIZE 1024

int main(int argc, char *argv[]) {
  mpg123_handle *handle;
  /* uint8_t buf[BUFSIZE]; // */
  char buf[BUFSIZE]; //
  if (argc <= 1) {
    fprintf(stderr, "Error!\nThis program requires the path of the mp3 files "
                    "as an argument!\n");
  } else {
    printf("%s\n", argv[1]);
  }

  handle = mpg123_new(NULL, NULL);
  mpg123_open_fixed(handle, argv[1], 2, MPG123_ENC_SIGNED_16);

  size_t decoded = 1;
  /* 从 handle 里读取 bufsize 大小的数据到 buf 中 */
  mpg123_read(handle, buf, BUFSIZE, &decoded);

  pa_simple *s;
  pa_sample_spec ss;

  ss.format = PA_SAMPLE_S16NE;
  ss.channels = 2;
  ss.rate = 44100;

  /* 与声音服务器建立连接 */
  s = pa_simple_new(NULL, "mp3-player", PA_STREAM_PLAYBACK, NULL, "Audio", &ss,
                    NULL, NULL, NULL);

  /* 播放缓冲区 buf 里的内容 */
  pa_simple_write(s, buf, decoded, NULL);

  /* 播放结束,释放资源 */
  pa_simple_free(s);
  return 0;
}
#+end_src
上面的代码编译后可以运行,但是实际上可能没有任何声音,因为我们只读取了字节流数据前
1024 字节的数据,数据太少了,而且这些字节流数据是由音频文件解压缩,解码之后得到的,
所以1024字节的数据可能连个响都听不到,我们可以把 BUFSIZE 设置为 1024000 即
1000kb 的数据大小,然后再运行一次,我用来测试的音频文件可以播放大概 5 秒,而这个音
频文件时长270秒,大小为 4.1MB, 按照这个比例换算下,解压解码后的字节流数据总共约
52.7MB 的大小,下面是修改 BUFSIZE 后的代码:
#+begin_src C
/* mp3 player on linux */
#include <fmt123.h>
#include <mpg123.h>
#include <pulse/def.h>
#include <pulse/simple.h>
#include <stddef.h>
#include <stdint.h>
#include <stdio.h>

#define BUFSIZE 1024000
/* #define BUFSIZE 409600 */

int main(int argc, char *argv[]) {
  mpg123_handle *handle;
  /* uint8_t buf[BUFSIZE]; // */
  char buf[BUFSIZE]; //
  if (argc <= 1) {
    fprintf(stderr, "Error!\nThis program requires the path of the mp3 files "
                    "as an argument!\n");
  } else {
    printf("%s\n", argv[1]);
  }

  handle = mpg123_new(NULL, NULL);
  mpg123_open_fixed(handle, argv[1], 2, MPG123_ENC_SIGNED_16);

  size_t decoded = 1;
  /* 从 handle 里读取 bufsize 大小的数据到 buf 中 */
  mpg123_read(handle, buf, BUFSIZE, &decoded);

  /* 下面要与声音服务器建立连接,播放 buf 里的数据 */
  pa_simple *s;
  pa_sample_spec ss;

  ss.format = PA_SAMPLE_S16NE;
  ss.channels = 2;
  ss.rate = 44100;

  s = pa_simple_new(NULL, "mp3-player", PA_STREAM_PLAYBACK, NULL, "Audio", &ss,
                    NULL, NULL, NULL);

  pa_simple_write(s, buf, decoded, NULL);

  /* 播放完毕释放资源 */
  pa_simple_free(s);
  return 0;
}
#+end_src

代码成功运行后播放了大概 5 秒的音乐,这证明上面的代码可以运行,并能完成播放功能.接
着我们就要让程序能够完整播放一整首歌曲. 完成播放整首的功能关键在于 mpg123_read()
和 pa_simple_write() 函数,前者从解码器句柄里读取音频文件经过处理后的字节流数据,
后者将数据传送到硬件,上面我们只读取了 BUFSIZE 大小的数据,并进行了播放,想要完整播
放,只需不断读取和播放就行了, mpg123_read() 的第四个参数是用于储存实际解码的字节
数的参数的地址,就是说该函数会将实际解码的字节数储存到该地址里,只要文件没有读取到
结尾,该字节数都一定会是大于0的,所以可以根据它来判断音频文件是否播放到结尾了,我们
可以利用一个 while 循环,循环结束的判断条件就是 mpg123_read() 的第三个参数是否大
于0,修改后的代码:
#+begin_src C
/* mp3 player on linux */
#include <fmt123.h>
#include <mpg123.h>
#include <pulse/def.h>
#include <pulse/simple.h>
#include <stddef.h>
#include <stdint.h>
#include <stdio.h>

#define BUFSIZE 1024
/* #define BUFSIZE 409600 */

int main(int argc, char *argv[]) {
  mpg123_handle *handle;
  /* uint8_t buf[BUFSIZE]; // */
  char buf[BUFSIZE]; //
  if (argc <= 1) {
    fprintf(stderr, "Error!\nThis program requires the path of the mp3 files "
                    "as an argument!\n");
  } else {
    printf("%s\n", argv[1]);
  }

  handle = mpg123_new(NULL, NULL);
  mpg123_open_fixed(handle, argv[1], 2, MPG123_ENC_SIGNED_16);

  size_t decoded = 1;
  /* 从 handle 里读取 bufsize 大小的数据到 buf 中 */
  mpg123_read(handle, buf, BUFSIZE, &decoded);

  pa_simple *s;
  pa_sample_spec ss;

  ss.format = PA_SAMPLE_S16NE;
  ss.channels = 2;
  ss.rate = 44100;

  s = pa_simple_new(NULL, "mp3-player", PA_STREAM_PLAYBACK, NULL, "Audio", &ss,
                    NULL, NULL, NULL);

  while (decoded > 0) {
    mpg123_read(handle, buf, BUFSIZE, &decoded);
    pa_simple_write(s, buf, decoded, NULL);
  }
  /* 播放完毕释放资源 */
  pa_simple_free(s);
  return 0;
}
#+end_src
** Makefile
用于编译上面最终代码的 Makefile:
#+begin_src makefile
play_test: play_test.o
	gcc -o play_test play_test.o -lmpg123 -lpulse -lpulse-simple
paly_test.o:play_test.c
	gcc play_text.c -o play_test.o
clean:
	rm play.o play
#+end_src
